### ISSUE TITLE
Error caused on mouse up

### ISSUE THREAD

**Issue by ColColonCleaner** [iosscripts/iosslider#48] opened 2012-07-03 22:04 UTC
When dragging the slider in my instance, on mouseup/release slider is throwing an error. Not sure why, or if it is affecting anything, but here is the error. I see no adverse effects. 

Uncaught TypeError: Cannot read property '0' of undefined                (  jquery.iosslider.min.js:35)
L.init.each.b.bind.b.css.cursor                    (  jquery.iosslider.min.js:35)
jQuery.extend.each                     (  jquery-1.7.2.js:660)
jQuery.fn.jQuery.each                    (  jquery-1.7.2.js:271)
L.init                               ( jquery.iosslider.min.js:35)
jQuery.event.dispatch                        ( jquery-1.7.2.js:3332)
jQuery.event.add.elemData.handle.eventHandle                      ( jquery-1.7.2.js:2941)

**Comment by iosscripts** [comment] 2012-07-03 23:10
Can you get cause error again but run the non-minified version? That would tell us what's happening I think.

**Comment by iosscripts** [comment] 2012-07-04 15:01
This may be a duplicate of issue #43 which was just resolved. If you don't mind, can you download v1.0.7 on the master branch and try that?

**Comment by ColColonCleaner** [comment] 2012-07-09 20:13
It works. Thanks.

**Closed as completed** 2012-07-09 20:14 UTC
Labels: Core, Troubleshooting
