### ISSUE TITLE
Text display problem on Android, Safari

### ISSUE THREAD

**Issue by Batmensch** [iosscripts/iosslider#42] opened 2012-07-03 01:04 UTC
Certain webkit-based browsers seem to have problems with displaying text on slides after the first slide.  For example, the following URL should display two slides of text, but on Safari Version 5.1.7 (7534.57.2) and in the standard Android browser only the first slide's text is shown.  Graphics on the slides would display properly.  

http://devenv61-temp.aldon.com/slider-test/

This is iosSlider 0.9.4.5, but 1.0 has the same issue.

If I open the "Web Inspector" and click the checkbox of any CSS property in the file, the 2nd slide text will appear.

The text renders properly in the Chrome browsers (even on Android), and it renders properly in the nightly Webkit builds.

**Comment by iosscripts** [comment] 2012-07-03 03:07
Something weird going on with your divs actually. Everything is rendering ok, its just drawing outside the visible area (you can tell by looking in the web inspector). 

Set a height attribute to the css of task_holder_task_id like so:

.task_holder_task_id {
    height: auto;
}

.task_holder_task_id {
    height: 16px;
}

**Comment by Batmensch** [comment] 2012-07-03 18:14
Making the changes you mention doesn't make a difference, Marc.  The demo above is now using height:16px; within the .task_holder_task_id class (height:auto has the same problem, though).  

Also, the first slide also uses .task_holder_task_id in the same place, and it displays fine.

**Comment by iosscripts** [comment] 2012-07-03 18:23
This is very odd indeed. Give me a bit more time to hammer out a solution.

**Comment by iosscripts** [comment] 2012-07-03 18:35
I was able to reproduce your issue in my own test case. Not sure why it's happening :S. I'm wondering why you need to put position: relative on .slide, .task_holder, and .task_holder_task_id? If you position: relative from all 3 it shows again.

Alternatively, I also got it working by adding position: absolute; and top: 0; to the anchor within .task_holder_task_id.

I think the root of the issue is the CSS is just too loose. Let me know if that helps :). I will leave the issue open until you say so.

**Comment by Batmensch** [comment] 2012-07-03 22:42
I'm sorry, I don't understand " If you position: relative from all 3 it shows again." Do you mean remove position:relative from all three?  And thank you for working on this!

**Comment by iosscripts** [comment] 2012-07-03 23:09
yes; I mean remove. Sorry. Did you try that?

**Comment by Batmensch** [comment] 2012-07-03 23:26
Yes.  Removing position:relative on each of those classes makes them appear.  Of course, they are in the wrong position when I do that!

**Comment by Batmensch** [comment] 2012-07-03 23:59
OK, so I can center those elements by using position:absolute and setting left: and right: positions.  I have a workaround.  Plus, evidently this problem is fixed in later versions of Webkit anyway (it's fixed in Chrome and in the Webkit nightlies now).

**Comment by iosscripts** [comment] 2012-07-04 00:20
Sorry you had to do a workaround... That kind of sucks. I'll close this for now, feel free to reply if your issues continue.

**Closed as completed by iosscripts** 2012-07-04 00:20 UTC
Labels: Core, Troubleshooting
