### ISSUE TITLE
Momentum breaks after using navPrevSelector, navNextSelector or navSlideSelector

### ISSUE THREAD

**Issue by theoldschooler** [iosscripts/iosslider#234] opened 2013-04-01 15:59 UTC
Platform: Safari on iPad, iOS 6.1.2 
iosSlider version: 1.2.2

When an iosSlider is launched with navPrevSelector, navNextSelector or navSlideSelector configured and you scroll using touch, the momentum feature works fine.

However, if you use any of the the navigation buttons first, and then try to touch scroll there is no momentum and the slider immediately stops after you lift your finger.

**Comment by marcwhitbread** [comment] 2013-04-01 16:04
All anchor links are currently causing the touchend event to be ignored. I'm looking into the cause. Duplicate of issue #220. 

Subscribe to issue #220 for a notification when the fix comes out.

**Closed as completed by marcwhitbread** 2013-04-01 16:04 UTC
