### ISSUE TITLE
Vertical slider

### ISSUE THREAD

**Issue by jackdent** [iosscripts/iosslider#140] opened 2012-10-26 13:51 UTC
Feature request: a way to adapt the slider so that it operates vertically, as well as horizontally

**Comment by ColColonCleaner** [comment] 2012-10-26 20:55
This is in development right now, hopefully in the same plugin but by what i'm hearing it will be separate.

**Comment by iosscripts** [comment] 2012-11-14 03:55
Closing, duplicate of issue #5.

**Closed as completed by iosscripts** 2012-11-14 03:55 UTC
Labels: Feature
