### ISSUE TITLE
Mouse wheel scroll for desktops

### ISSUE THREAD

**Issue by BCleverly** [iosscripts/iosslider#160] opened 2012-11-29 08:55 UTC
Ability to enable/disable Mouse wheel scroll on desktop with an additional option to slide by pixel or slides.

Able to use jQuery Mouse wheel plugin to achieve this. But a native solution would be much more appreciated.

**Comment by iosscripts** [comment] 2012-11-29 15:50
Thank you for the feature request. Try to keep an issue submission to a single question in future. I will answer your question below but remove it above to avoid confusion about the feature request.

> More of a query then a suggestion is it possible to have slide items of different widths? Haven't had a chance to play around properly to test for myself.

Yes. Simply define the width for the slide elements in your CSS.

**Comment by iosscripts** [comment] 2012-11-29 15:53
Actually, this is a duplicate of issue #58. So I will close this and recommend you follow that one in stead.

**Closed as completed by iosscripts** 2012-11-29 15:53 UTC
Labels: Feature
